# Generated by Django 2.2 on 2019-12-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserJobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_assigned', to='UserJobsApp.Users'),
        ),
    ]
